# Generated by Django 3.0.2 on 2020-07-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_class_id', models.IntegerField()),
                ('product_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('brand_name', models.CharField(blank=True, max_length=60, null=True)),
                ('product_name', models.CharField(max_length=60)),
                ('sku', models.BigIntegerField(db_column='SKU')),
                ('srp', models.DecimalField(blank=True, db_column='SRP', decimal_places=4, max_digits=10, null=True)),
                ('gross_weight', models.FloatField(blank=True, null=True)),
                ('net_weight', models.FloatField(blank=True, null=True)),
                ('recyclable_package', models.BooleanField(blank=True, null=True)),
                ('low_fat', models.BooleanField(blank=True, null=True)),
                ('units_per_case', models.SmallIntegerField(blank=True, null=True)),
                ('cases_per_pallet', models.SmallIntegerField(blank=True, null=True)),
                ('shelf_width', models.FloatField(blank=True, null=True)),
                ('shelf_height', models.FloatField(blank=True, null=True)),
                ('shelf_depth', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
    ]
